
MODEL:
  PR_ENCODER:
    NAME: PREncoder
    BATCH_SIZE: 12
    CONTEXT_LENGTH: 1024
    HIDDEN_SIZE: 768
    NUM_HIDDEN_LAYERS: 12
    NUM_ATTENTION_HEADS: 12
    INTERMEDIATE_SIZE: 3072
    HIDDEN_ACT: "gelu"
    HIDDEN_DROPOUT_PROB: 0.0
    ATTENTION_PROBS_DROPOUT_PROB: 0.0
    INITIALIZER_RANGE: 0.02
    LAYER_NORM_EPS: 0.000000000001
    IMAGE_SIZE: [224, 224]
    PATCH_SIZE: 16
    NUM_CHANNELS: 3
    QKV_BIAS: True
    RESCALE_EVERY: 6
    ENCODER_STRIDE: 16
    MLP_RATIO: 4

  PR_DECODER:
    NAME: PRDecoder
      
    HIDDEN_SIZE: 768
    OUTPUT_SIZE: 6
    MLP_RATIO: 4
    HIDDEN_ACT: "gelu"
